### PR TITLE
Fix typo in authorization header

### PR DESCRIPTION
**Pull request by FuzzyMistborn**
Remove "f" before bearer

### CODE REVIEW

**Comment by anthonylavado** [comment]
How about that... totally missed that this whole time, and yet it’s been working.

LGTM, but we’ll run this by the boss. @mike-grant?

**Comment by mike-grant** [comment]
Unfortunately this isn't a typo, it's string interpolation in python 3.4

**Comment by anthonylavado** [comment]
And that’s why:
1. I requested a review from Mike
2. I need to finish learning Python

Cheers!

**Comment by FuzzyMistborn** [comment]
D'oh!  I've been having issues with switching over to tokens so I chalked it up to my issues.  All I needed was the F.  (and I too need to finish learning Python)

**Pull request closed without merging**
